---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangjinshan.
--- DateTime: 2020/8/11 10:18
---
local typedefs = require "kong.db.schema.typedefs"
local string_array = {
  type = "array",
  default = {},
  elements = { type = "record",
               fields = {
                 { host = { type = "string", required = true }, },
                 { port = { type = "number", required = true }, },
                 { weight = { type = "number", required = false }, },
               },
             },
}

local colon_string_array = {
  type = "array",
  default = {},
  --elements = { type = "string", },
  elements = typedefs.cidr_v4,
}

local one_of = {
  type = "string",
  default = "header",
  one_of = { "header", "cookie", 'args' }
}

local ip_canary_record = {
  type = "record",
  fields = {
    { range = colon_string_array },
    { upstream = { type = "string" } },
  },
}

local uid_canary_record = {
  type = "record",
  fields = {
    { on = one_of },
    { name = { type = "string", default = "uid" } },
    { range = string_array },
    { upstream = { type = "string" } },
  }
}

local canary_on_record = {
  type = "record",
  fields = {
    { on = one_of },
    { name = { type = "string", } },
    { range = string_array },
    { upstream = { type = "string" } },
  }
}

return {
  name = "loadbalance",
  fields = {
    { protocols = typedefs.protocols_http },
    { config = {
      type = "record",
      fields = {
        { loadbalance_upstream = string_array },
        { algorithm = { type = "string", default = 'default' },},
      },
    },
    },
  },
}
