---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangjinshan.
--- DateTime: 2020/8/11 10:18
---

local function test(ranges, value)
  if ranges and type(ranges) == 'table' then
    local _len = #value
    for _, v in ipairs(ranges) do
      local result = string.match(value, v)
      if result and #result == _len then
        kong.log.notice('v:', v)
        return true
      end
    end
  end
  return false
end

return { match = test }
