---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangjinshan.
--- DateTime: 2020/8/11 10:18
---
local DefaultLoadBalance = require "kong.plugins.loadbalance.policies.DefaultLoadBalance"
local WeightLoadBalance = require "kong.plugins.loadbalance.policies.WeightLoadBalance"
local RobinLoadBalance = require "kong.plugins.loadbalance.policies.RobinLoadBalance"
return {
  ['default'] = {
    handler = function(fallback, conf)
      local DefaultLoadBalance = DefaultLoadBalance:new(nil, conf)
      return DefaultLoadBalance:handler(fallback);
    end
  },
  ['weight'] = {
      handler = function(fallback, conf)
          local WeightLoadBalance = WeightLoadBalance:new(nil, conf)
          return WeightLoadBalance:handler(fallback);
      end
  },
  ['robin'] = {
      handler = function(fallback, conf)
          local RobinLoadBalance = RobinLoadBalance:new(nil, conf)
          return RobinLoadBalance:handler(fallback);
      end
  }



}
