---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangjinshan.
--- DateTime: 2020/8/14 14:27
---
local IPCanary = require "kong.plugins.canary.policies.IPCanary"
local HeaderCanary = require "kong.plugins.canary.policies.HeaderCanary"
local QueryCanary = require "kong.plugins.canary.policies.QueryCanary"
local CookieCanary = require "kong.plugins.canary.policies.CookieCanary"

return {
  ['ip'] = {
    handler = function(fallback, conf)
      local IPCanary = IPCanary:new(nil, conf);
      return IPCanary:handler(fallback);
    end
  },
  ['header'] = {
    handler = function(fallback, conf)
      local HeaderCanary = HeaderCanary:new(nil, conf);
      return HeaderCanary:handler(fallback);
    end
  },
  ['query'] = {
    handler = function(fallback, conf)
      local QueryCanary = QueryCanary:new(nil, conf);
      return QueryCanary:handler(fallback);
    end
  },
  ['cookie'] = {
    handler = function(fallback, conf)
      local CookieCanary = CookieCanary:new(nil, conf);
      return CookieCanary:handler(fallback);
    end
  }
}
