---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangjinshan.
--- DateTime: 2020/08/14 16:21
---
local utils = require 'kong.plugins.canary';
local cjson = require "cjson"
local cmatch = require 'kong.plugins.canary.policies.cmatch';
local BaseCanary = require 'kong.plugins.canary.policies.BaseCanary';

local policy = "query";

local QueryCanary = BaseCanary:new();

function QueryCanary:new(o, conf)
  o = o or BaseCanary:new(o, policy, conf)
  setmetatable(o, self);
  self.__index = self;
  return o;
end

function QueryCanary:handler(fallback)
  if not self.conf.query or #self.conf.query == 0 then
    return 'next', policy
  end

  local querys = self.conf.query
  for i = 1, #querys do
    if querys[i].name and querys[i].range and #querys[i].range>0 then
      local values = utils[policy].getValue(querys[i].name)
      kong.log.notice('conf.name:', querys[i].name, ',value:', cjson.encode(values))
      if type(values) == 'string' then
        if cmatch.match(querys[i].range, values, querys[i].matchType) then
          kong.service.set_target(querys[i].upstream.host,querys[i].upstream.port)
          kong.log.notice('Canary policy is ', policy, ',Canary host:', querys[i].upstream.host);
          return 'end', policy
        end
      elseif type(values) == 'table' then
        for _, v in ipairs(values) do
          if cmatch.match(querys[i].range, v, querys[i].matchType) then
            kong.service.set_target(querys[i].upstream.host,querys[i].upstream.port)
            kong.log.notice('Canary policy is ', policy, ',Canary host:', querys[i].upstream.host);
            return 'end', policy
          end
        end
      end
    end
  end

  -- uid upstream is not nil
  return 'next', policy
end

return QueryCanary;
