---
--- Generated by Luanalysis
--- Created by wang.jinshan3.
--- DateTime: 2024/1/26 9:58
---

--local result = string.match("S。D-00131223312","^S2.+")
local result = string.match("31233322233321","%d.+")
--local result = string.match("helle world 123","[%w%d]+ [%w%d]+ %d+")
print("result:",result)